name: Post to X every 2 hours

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  post:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: post-to-x
      cancel-in-progress: false
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      PROVIDER_BASE_URL: ${{ secrets.PROVIDER_BASE_URL }}
      PROVIDER_API_KEY: ${{ secrets.PROVIDER_API_KEY }}
      PROVIDER_MODEL: ${{ secrets.PROVIDER_MODEL }}
      MAX_LENGTH: 220
      DRY_RUN_DEFAULT: 'false'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fail fast if provider not configured
        run: |
          if [ -z "${PROVIDER_API_KEY}" ] || [ -z "${PROVIDER_BASE_URL}" ] || [ -z "${PROVIDER_MODEL}" ]; then
            echo "Provider not configured (PROVIDER_* secrets missing)."
            exit 1
          fi

      - name: Post
        timeout-minutes: 5
        run: |
          python -m bot post "Drop a random motivational quote, feel free to look up one on the internet or make some shit up. Also be direct a use some vulgar language" --engine provider --no-dry-run
